# Generated by Django 5.1.5 on 2025-02-20 01:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_reset_token_customuser_reset_token_expiry'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='security_answer_1',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='security_answer_2',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='security_question_1',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='security_question_2',
        ),
    ]
